env = Environment()
env.Append(CPPPATH = ['/usr/include/'])
env.Append(CPPFLAGS = '-fpermissive')
env.Append(LIBPATH = ['/usr/lib'])
env.Append(LIBS = ['GL','glut','GLU'])
env.Program(target = 'bin/lab1Graph', source = 'src/main.cpp')
